version: '3.8'

services:
  app:
    build: .
    container_name: python_app
    volumes:
      - ./app:/app  # ホストのappフォルダをコンテナの/appにマウント
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
